#-------------------------------
# Site Settings
title: Tromleorkestret
logo: # You can add own logo. For example '/images/logo.png'.
description: Tromleorkestret â€“ The Firespewing Music Machine


#-------------------------------
# Navigation Settings
menu-settings:
  menu-items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'
    - title: 'Music'
      url: '/music/'  
    - title: 'Shows'
      url: '/shows/'
    - title: 'People'
      url: '/people/'
    - title: 'Contact'
      url: '/contact/'
    - title: 'Robotic-Audio'
      url: 'http://www.roboticaudio.com/'
#    - title: 'Style Guide'
#      url: '/styleguide/'


#-------------------------------
# Author Settings
author:
  name: HJALTE BESTED HJORTH
  avatar: '/images/tromleorkestret/TrorkMV1.jpg'


#-------------------------------
# Hero Settings
hero:
  title: TROMLEORKESTRET
  description: The Firebreathing Music Machine
  #image: '/images/tromleorkestret/TrorkMV2.jpg'
  image: '/images/himmelstorm/Himmelstorm1.jpg'



#-------------------------------
# Contact Settings
contact:
  email: hjalte.bested.hjorth@email.com # Add your email for contact form
  description: Norlin comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Norlin theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Footer section
social:
#- {icon: "fa-brands fa-x-twitter", name: "Twitter", link: "https://twitter.com"}
- {icon: "fa-regular fa-envelope", name: "Email", link: "mailto:hjalte.bested.hjorth@gmail.com"}
- {icon: "fa-brands fa-facebook-f", name: "Facebook", link: "https://facebook.com/tromleorkestret"}
#- {icon: "fa-brands fa-dribbble", name: "Dribbble", link: "https://dribbble.com"}
- {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://instagram.com/tromleorkestret"}
#- {icon: "fa-brands fa-pinterest", name: "Pinterest", link: "https://pinterest.com"}
- {icon: "fa-brands fa-youtube", name: "Youtube", link: "https://youtube.com/@tromleorkestret"}
#- {icon: "fa-brands fa-vimeo-v", name: "Vimeo", link: "https://vimeo.com/"}
- {icon: "fa-brands fa-soundcloud", name: "SoundCloud", link: "https://on.soundcloud.com/6CzYVZ2fXJKGqsiN7"}

social-hjalte:
- {icon: "fa-regular fa-envelope", name: "Email", link: "mailto:hjalte.bested.hjorth@gmail.com"}
- {icon: "fa-brands fa-facebook-f", name: "Facebook", link: "https://facebook.com/hjalte.hjorth"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/robotic4udio"}
- {icon: "fa-brands fa-linkedin", name: "LinkedIn", link: "https://dk.linkedin.com/in/hjalte-bested-moeller"}

social-sofie:
- {icon: "fa-regular fa-envelope", name: "Email", link: "mailto:sofie.hjorth@gmail.com"}
- {icon: "fa-brands fa-facebook-f", name: "Facebook", link: "https://facebook.com/sofie.schausen"}
- {icon: "fa-brands fa-instagram", name: "Instagram", link: https://www.instagram.com/sofie._.hjorth}
- {icon: "fa-brands fa-linkedin", name: "LinkedIn", link: "https://dk.linkedin.com/in/sofie-hjorth-schausen-7570787a"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://mastodon.social/"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: hjaltebestedhjorth # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp-identifier: # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
mailchimp-button-text: Join